# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '自定义弹出按钮和方向' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry', '~> 1.0.2'
  # Pods for 自定义弹出按钮和方向

  target '自定义弹出按钮和方向Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '自定义弹出按钮和方向UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
